const calendar = [
	{ type: "event", title: "Welcome Party!", info: "Welcome party for new members! Its been some time since school started again, but  its never to late to have a welcome party to get to know the new members of the team! Lets gather to have a good time, meet new people, and party the night away. Make sure to bring some good vibes. PS: puking should happen outside.", date: "2019-10-05", time: "14:15", location: "Solsiden", link:"2019-10-05-welcome-party", tag: "Social" },
	{ type: "practice", title: "Group Practice #17", info: "Today: Tweaking. Instructor: Harald Gress", date: "2019-10-16", time: "18:00", location: "Gløshaugen", link:"", tag: "Practice" },
	{ type: "practice", title: "Group Practice #16", info: "Today: Speed. Instructor: Harald Gress", date: "2019-10-13", time: "18:00", location: "Tyholt", link:"", tag: "Practice" },
	{ type: "practice", title: "Group Practice #15", info: "Today: Drifting. Instructor: Harald Gress", date: "2019-10-09", time: "18:00", location: "Gløshaugen", link:"", tag: "Practice" },
	{ type: "event", title: "Drifting fun!", info: "Drifting spectacular. Instructor: Harald Gress Lorem ipsum dolor sit amet, consectetur adipisicing elit. Esse ex nam quo reprehenderit. Ad alias amet at blanditiis cupiditate debitis delectus ea eligendi eum facilis inventore qui repellendus unde, vel. Lorem ipsum dolor sit amet, consectetur adipisicing elit.", date: "2020-01-06", time: "18:00", location: "Solsiden", link:"2020-01-06-drifting-fun", tag: "Social" },
	{ type: "event", title: "Party at mine", info: "It's that time of year again! No, not Christmas (yet). ITS HALLOWEEN. THE SPOOKIES TIME OF YEAR. And it's time to party. It's my honor to invite the entire team  home to me and party the spooky night away into christmas! \n" +"Dress code: costumes (spooky or sexy or funny, everyone is accepted)", date: "2019-10-31", time: "19:00", location: "Samfundet", link:"2019-10-31-party-at-mine", tag: "Social" },
	{ type: "event", title: "Lets make some money", info: "Time to make some money for this rockin' team!\n" +"During this Sunday a fundraiser will be held. We'll sell cakes, waffles, coffee and 'lodd' where you can win some sweet prices! Invite your friends and family. Hope to see you there. ", date: "2019-10-30", time: "18:00", location: "Gløshaugen", link:"2019-10-30-lets-make-some-money", tag: "Fundraiser" },
	{ type: "event", title: "Big competition in Oslo", info: "The coming week there will be held the annual Norwegian Winter Lawnracers Race  (NWLR) for the 3rd time. The group registered to compete will travel together by train on Friday, whilst the lawnmowers will be shipped in a big trailer (like in Cars, the movie). When we arrive in Oslo, will go to the hotel together (unless you have somewhere else to sleep), and have a \"quiet\" night in. The weekend will be dedicated to racing and some socializing.  A party can be guaranteed! Hope to see you there :)", date: "2019-11-15", time: "18:00", location: "Oslo", link:"2019-10-05-big-competition-in-oslo", tag: "Competition" },
	{ type: "practice", title: "Group Practice #18", info: "Today: Drifting. Instructor: Harald Gress", date: "2019-10-20", time: "18:00", location: "Gløshaugen", link:"", tag: "Practice" },
	{ type: "practice", title: "Group Practice #19", info: "Today: Speed. Instructor: Harald Gress", date: "2019-10-23", time: "18:00", location: "Gløshaugen", link:"", tag: "Practice" },
	{ type: "practice", title: "Group Practice #20", info: "Today: Tweaking. Instructor: Harald Gress", date: "2019-10-27", time: "18:00", location: "Gløshaugen", link:"", tag: "Practice" },
	{ type: "practice", title: "Group Practice #21", info: "Today: Speed. Instructor: Harald Gress", date: "2019-10-30", time: "18:00", location: "Gløshaugen", link:"", tag: "Practice" },
	{ type: "practice", title: "Group Practice #22", info: "Today: Drifting. Instructor: Harald Gress", date: "2019-11-03", time: "18:00", location: "Gløshaugen", link:"", tag: "Practice" },
];
const news = [
  {
    title: "Welcome, new members!",
    id: "welcome-new-members", //makes it easier to create short-forms to use for id and anchor links //other possible solution: using split to remove whitespace and characters that are not letter -> get first 6 letters to make id/anchor link
    date: "2019-09-15",
    info: "A new semester has started, and new members have joined us. It's time to (officially) welcome the new members! We, here at LMR, hope that you are enjoying practicing with our team and that you already love the sport as much as we do. Until now it has been quite hectic, but the practices will soon fall into their normal routine. We recommend all new players read the rulebook (which can be found online, just a google search away). We hope to see you all next practice, and on all the practices, competitions and social events after that!"
  },
  { title: "Greet the new coach!", id: "greet-the-new-coach", date: "2019-09-29", info: "We are very proud to introduce our new coach to the team! Ellen Klipp has extensive experience from coaching teams in the US and is dedicated to helping our team and athletes continue to grow and improve. Please give her a warm welcome in true LMR spirit!" },
  { title: "Tshirts available", id: "tshirts-available", date: "2019-10-06", info: "Finally they have arrived! The new team t-shirts are here and they are fantastic! If you don't believe it yet, they will be available at next practice, both to view and order one for yourself. You can also contact us on e-mail to order yours today! Get matching outfits for the whole team!" },
  { title: "Rule change", id: "rule-change", date: "2019-10-22", info: "Our organization plays by the US lawnmower racing rules. The official board has updated their (international) US rulebook. We advise every athlete, coach and member of the staff to read the updated version of the rulebook. The rulebook can be found on this site: <a href='http://letsmow.com/rules-tech/official-rules/' target='_blank' rel='noopener'>letsmow.com</a>" },
  { title: "Have YOU seen the spooky ghost?", id: "spooky-scary", date: "2019-10-31", info: "Halloween is upon us and so are the ghosts... This year, the ghost of the court, has been particularly fond of pranking us. Equipment have been 'misplaced' or hidden, mowers are starting up of their own, and one member of the staff even saw a mower taking off on its own! Even so, the most frightening sight was when a couple of our new athletes were on their way home. Taking the shortcut over the field, talking amongst each other, the wind suddenly started howling. All of a sudden they saw a ghostly shape on the court in front of them. The ghost, known as 'The Mower', sat on a ghost lawnmower, which took off faster than we have ever been able to on our own real lawnmowers, and disappeared... 'The Mower' have a history of pranking the team, and likes to freak out new members, but it has never done any real harm, so you don't need to worry! Walk safe and happy halloween!" },
  { title: "Competition qualification", id: "competition-qualification", date: "2019-11-10", info: "Congratulations to our members that qualified for the national competition at Gresstun! Thank you for an amazing weekend and race, making it really interesting for the spectators to watch. We wish you all the best with upcoming practices and the new competition." },
];
